const langData = {
  enUS: {
    home: {
      home: 'Home',
      explore: 'Explore',
      language: 'EN',
      safemint: 'Safemint',
      desc: 'Open, community-driven, on-chain SBT certificate platform',
      desc1: 'one-stop solution',
      desc2: 'dao governance',
      desc3: 'on-chain SBT certification',
      contact: 'Contact US',
      api: 'Security API',
      advantages: 'Our Advantages',
      'adv-desc': 'Efficient community-driven and standard pipeline workflow',
      audit: 'Safemint nft smart-contract security audit',
      processing: 'Processing',
      'audit-processing1': 'submit confirmed requiremen',
      'audit-processing2': 'create / assgin code check task',
      'audit-processing3': 'deliver verified result onchain',
      'audit-processing4': 'SBT certificate',
      pricing: 'Pricing',
      'audit-pricing1': 'base price  + package pricing',
      solution: 'Solution',
      'audit-solution1': 'coummnity pipeline Expert Review',
      traditional: 'Tranditional smart-contract security audit',
      'traditional-processing1': 'share source code',
      'traditional-processing2': 'receive quote',
      'traditional-processing3': 'Begin Vulnerability Inspection',
      'traditional-processing4': 'Suggest Remediations',
      'traditional-processing5': 'Deliver Report',
      'traditional-pricing1':
        'final price  = base price + workload + complexity according to some indicator（line of codes, business logic complexity etc）',
      'traditional-solution1': 'Formal Verfication Engine + Expert Review',
      stat1: 'Public chains supported',
      stat2: 'Onchain verified project',
      stat3: 'Onchain-risk assement',
      how: 'How we work',
      'how-desc':
        'according to the different demands of customers,safemint will customerized the audit business.',
      'how-general': 'general business cooperation process:',
      'how-step1': 'requriement confirm',
      'how-step2': 'pricing calculate',
      'how-step3': 'report(option)',
      'how-step4': 'onchain result',
      partners: 'Partners & Investor',
      projects: 'Projects'
    },
    explore: {
      title: 'Explore Certificated Projects'
    }
  },
  zhCN: {
    home: {
      home: '首页',
      explore: '探索',
      language: '中文',
      safemint: 'Safemint',
      desc: 'Open, community-driven, on-chain SBT certificate platform',
      desc1: 'one-stop solution',
      desc2: 'dao governance',
      desc3: 'on-chain SBT certification',
      contact: 'Contact US',
      api: 'Security API',
      advantages: 'Our Advantages',
      'adv-desc': 'Efficient community-driven and standard pipeline workflow',
      audit: 'Safemint nft smart-contract security audit',
      processing: 'Processing',
      'audit-processing1': 'submit confirmed requiremen',
      'audit-processing2': 'create / assgin code check task',
      'audit-processing3': 'deliver verified result onchain',
      'audit-processing4': 'SBT certificate',
      pricing: 'Pricing',
      'audit-pricing1': 'base price  + package pricing',
      solution: 'Solution',
      'audit-solution1': 'coummnity pipeline Expert Review',
      traditional: 'Tranditional smart-contract security audit',
      'traditional-processing1': 'share source code',
      'traditional-processing2': 'receive quote',
      'traditional-processing3': 'Begin Vulnerability Inspection',
      'traditional-processing4': 'Suggest Remediations',
      'traditional-processing5': 'Deliver Report',
      'traditional-pricing1':
        'final price  = base price + workload + complexity according to some indicator（line of codes, business logic complexity etc）',
      'traditional-solution1': 'Formal Verfication Engine + Expert Review',
      stat1: 'Public chains supported',
      stat2: 'Onchain verified project',
      stat3: 'Onchain-risk assement',
      how: 'How we work',
      'how-desc':
        'according to the different demands of customers,safemint will customerized the audit business.',
      'how-general': 'general business cooperation process:',
      'how-step1': 'requriement confirm',
      'how-step2': 'pricing calculate',
      'how-step3': 'report(option)',
      'how-step4': 'onchain result',
      partners: 'Partners & Investor',
      projects: 'Projects'
    }
  }
}

export default langData
